### ISSUE TITLE
Sensor error Home Assistant 2023.6.0

### ISSUE THREAD

**Issue by MVB1989** [nick2525/broadlink_s1c_s2c#12]
After the last update, this error appears and my sensors from broadlink s1c no longer work.
With the previous version they worked perfectly

Logger: homeassistant.loader
Source: custom_components/broadlink_s1c/sensor.py:78
Integration: broadlink_s1c (documentation, issues)
First occurred: 09:23:14 (1 occurrences)
Last logged: 09:23:14

Unexpected exception importing platform custom_components.broadlink_s1c.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/broadlink_s1c/sensor.py", line 78, in <module>
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'

**Comment by albxox** [comment]
same here
After the last update to Home Assistant 2023.6.0, this error appears and my sensors from broadlink s1c no longer work.
With the previous version they worked perfectly

**Comment by MVB1989** [comment]
https://community.home-assistant.io/t/broadlink-s1c-alarm-kit-custom-sensor-component/45980/215?u=mvb1989

**Comment by Yonny24** [comment]
Thanks that fixed it for me

**Comment by PcOnline2004** [comment]
Error with HA 2023.6.3
------------
A basic validation of the configuration is automatically done before restarting. The basic validation ensures the YAML configuration doesn't have errors which will prevent Home Assistant or any integration from starting. It's also possible to only do the basic validation check without restarting.
Configuration invalid!
Platform error sensor.broadlink_s1c - Exception importing custom_components.broadlink_s1c.sensor
Platform error sensor.broadlink_s1c - Exception importing custom_components.broadlink_s1c.sensor
------------------
