### ISSUE TITLE
Will it work?

### ISSUE THREAD

**Issue by rucanunes** [nick2525/broadlink_s1c_s2c#2]
Hello,

Could someone please tell me if this integration will work with this version of HA?
[https://github.com/home-assistant/operating-system/releases/download/5.13/hassos_rpi4-64-5.13.img.xz](url)

**Comment by rucanunes** [comment]
Installed just now and got this:
Using HA from https://github.com/home-assistant/operating-system/releases/download/5.13/hassos_rpi4-64-5.13.img.xz
with a Raspberry. 
Core-2021.4.0
Python | 3.8.7
OS: 5.4.83-v8
aarch64

`
Logger: homeassistant.components.sensor
Source: custom_components/broadlink_s1c/sensor.py:184
Integration: Sensor (documentation, issues)
First occurred: 16:02:27 (1 occurrences)
Last logged: 16:02:27
Error while setting up broadlink_s1c platform for sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 205, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/asyncio/coroutines.py", line 124, in coro
    res = func(*args, **kw)
  File "/config/custom_components/broadlink_s1c/sensor.py", line 90, in async_setup_platform
    conn_obj = HubConnection(ip_address, mac_addr, timeout)
  File "/config/custom_components/broadlink_s1c/sensor.py", line 173, in __init__
    self._authorized = self.authorize()
  File "/config/custom_components/broadlink_s1c/sensor.py", line 184, in authorize
    auth = self._hub.auth()
  File "/usr/local/lib/python3.8/site-packages/broadlink/device.py", line 186, in auth
    response = self.send_packet(0x65, payload)
  File "/usr/local/lib/python3.8/site-packages/broadlink/device.py", line 267, in send_packet
    packet[0x24:0x26] = self.devtype.to_bytes(2, "little")
AttributeError: 'NoneType' object has no attribute 'to_bytes'
`

**Comment by nick2525** [comment]
it was fixed
